version: '3'

services:

  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.3.0
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
    #   hapi.fhir.tester.server_address: 'http://localhost:8080/fhir'
      hapi.fhir.fhir_version: R4
      hapi.fhir.cql_enabled: 'true'
      # fyi defaults to true anyway
      hapi.fhir.bulk_export_enabled: 'true'
      # websocket subs
      hapi.fhir.subscription.websocket.enabled: 'true'

      # none of this works...
      # hapi.fhir.partitioning: ''
      # hapi.fhir.partitioning.allow_references_across_partitions: 'false'
      # hapi.fhir.partitioning.cross_partition_reference_mode: 'true'
      # hapi.fhir.partitioning.multitenancy_enabled: 'true'
      # previous way
      # hapi.fhir.partitioning_multitenancy_enabled: 'true'

    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"