apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fhir
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: fhir
    spec:
      containers:
        - env:
            - name: profiles.active
              value: r4
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.datasource.password
              value: admin
            - name: spring.datasource.url
              value: jdbc:postgresql://db:5432/hapi
            - name: spring.datasource.username
              value: admin
          image: hapiproject/hapi:v5.2.1
          name: fhir
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
